### ISSUE TITLE
Better Documentation with more in-depth explanation? 

### ISSUE THREAD

**Issue by ghost** [adamthedeveloper/wepay-rails#1]
I am encountering some bug and I am almost 100% certain that it has something to do with the way I name my controllers and my routing configuration. 

Can you provide additional detail in the README? It would be great if you could list out your file names and routes.rb as well.

**Comment by adamthedeveloper** [comment]
Yeah.  The docs are in need of help. Ill write up better docs tomorrow. I
appreciate feedback so keep it coming
Adam
On Aug 17, 2011 2:54 AM, "vicngtor" <
reply@reply.github.com>
wrote:

**Comment by adamthedeveloper** [comment]
Actually, I'll post my setup that I am using tonight so you aren't held up. I introduced creating a checkout to wepay.rails a few days ago...haven't fully tested it though. It's getting close and I need to have it done for my project as well so any feedback you can give me will be really helpful.

Adam

**Comment by adamthedeveloper** [comment]
I've posted some more in depth explanation - more though is needed before this gem can be used. More code to handle all of the API wepay offers, more error handling, more documentation...Hang in there - it's coming.

**Comment by adamthedeveloper** [comment]
I am starting to build up the Wiki.

**Comment by adamthedeveloper** [comment]
Since the re-write and finalization of wepay-rails, documentation is complete and it should be very easy to implement wepay-rails into your app now.  Please try the latest version. If you run into any problems, please feel free to open a new ticket.
