### ISSUE TITLE
Tilde file went into the merge. Can you remove it?

### ISSUE THREAD

**Issue by adamthedeveloper** [adamthedeveloper/wepay-rails#11]
Sorry I didn't catch it sooner Steve. This is file to be removed:

lib/wepay-rails.rb~

Notice the '~'. Your IDE must have created and added a swap file.

While you are at it, please add a line to the contributors section of the README for yourself - that way, we don't have too many version updates.

Thanks again for you contributions.

Adam

**Comment by SteveAquino** [comment]
Ok I made the fix.  Do I need to update the VERSION and regenerate the gemspec for this?

**Comment by adamthedeveloper** [comment]
Sure. Just add to the patch level. Thanks again.

Adam
On May 26, 2012 1:00 PM, "Steve Aquino" <
reply@reply.github.com>
wrote:
