### ISSUE TITLE
Wiki clarifications needed

### ISSUE THREAD

**Issue by nborwankar** [adamthedeveloper/wepay-rails#13]
a) when I am using this multiple user dynamic auth approach, in the
 wepay.yml I only provide client_id and client_secret right? Because I don't
have a token yet and when I get token(s) there will be multiple and so the
yml as defined is somewhat tied to the single user case correct? Also
account_id comes after I get a token. So I dont have an account_id either.

 b) the wiki says at one point
 "Calling get_access_token with a valid access key in the params hash will
return the :access_toeknattribute, and also set the :account_id attribute to
the user's WePay user id."

 I assume "valid access key" refers to the 'code' param returned by WePay
which is in  params[:code]  yes?

Also it should be account_id not user id in the last few words yes?
account_id as returned by WePay when an account is created
via /v2/account/create yes?

Thanks much.

**Comment by SteveAquino** [comment]
Ok I've made the requested changes.  Thanks for pointing out the inconsistencies.
