### ISSUE TITLE
Store sensitive data in wepay.yml using embedded Ruby (.erb)

### ISSUE THREAD

**Issue by SteveAquino** [adamthedeveloper/wepay-rails#15]
Not sure the best way to handle this one, but I'd like to store sensitive data (namely production client_id and client_secret) in a variable and call it in wepay.yml with ruby.  This is trivial using yml.erb, however the initialization mechanism for WepayRails only looks for "wepay.yml" and thus fails when you add .erb to the file name.

I don't have much experience messing with YAML loading and such, but I found out how to load the file with .erb.  I'm sure there is a more elegant way to solve this but my proposed solution is to edit wepay-rails.rb as follows: 

```
class Engine < Rails::Engine
    # Initializers
    initializer "WepayRails.initialize_wepay_rails" do |app|
      yml = Rails.root.join('config', 'wepay.yml').to_s
      if File.exists?(yml)
        settings = YAML.load_file(yml)[Rails.env].symbolize_keys
      elsif File.exists?(yml+".erb")
        settings = YAML::load(ERB.new(IO.read(yml+".erb")).result)[Rails.env].symbolize_keys
      end
      Configuration.init_conf(settings) unless settings.nil?
    end

    ...
end
```

**Comment by SteveAquino** [comment]
I've updated my personal fork and things are working.  I think it makes sense to add some tests before we bump to version 2.3.0, so I will do that before pushing out changes.

**Comment by adamthedeveloper** [comment]
Your erb solution looks good to me.

**Comment by SteveAquino** [comment]
Ok I've pushed the update and added some basic tests.  It's pretty self explanatory but let me know if you think there should be a wiki entry for this.
