### ISSUE TITLE
Error when generating migrations

### ISSUE THREAD

**Issue by SachaG** [adamthedeveloper/wepay-rails#2]
With the wepay-rails gem installed, I get an error every time I run "rails generate migration":

```
/Users/Sacha/.rvm/gems/ruby-1.9.2-p180/gems/wepay-rails-0.1.114/lib/wepay-rails.rb:48:in `<class:Gateway>': uninitialized constant WepayRails::Payments::Gateway::HTTParty (NameError)
```

Any idea why that's happening? I'm quite new to Rails, so it's entirely possible that I've made a mistake somewhere, but as far as I can tell all I did was install the gem.

**Comment by SachaG** [comment]
OK, I figured out that I was missing the [HTTParty gem](https://github.com/jnunemaker/httparty).

**Comment by adamthedeveloper** [comment]
Hi SachaG,

  I wanted to let you know that I completely rewrote this gem and it's now complete. The best and latest version is 2.1.0. I hope you have a better time getting the latest version running. If you need anything, let me know.

Adam

**Comment by SachaG** [comment]
Thanks! In the end I didn't use WePay at all because it doesn't support non-US accounts. But I'll keep your gem in mind if they ever change their policy. Thanks for your hard work!
