### ISSUE TITLE
config/wepay.yml template outputs wrong endpoint keys

### ISSUE THREAD

**Issue by jmif** [adamthedeveloper/wepay-rails#22]
It looks like the wepay.yml file from install initializer outputs wepay_api_url for the WePay API endpoint, but the lib/wepay-rails.rb references @wepay_config[:wepay_api_endpoint] and @wepay_config[:wepay_ui_endpoint].  This is causing the all environments to default to WePay's production endpoint if you use the default configuration structure that is output by the install initializer. 

Everything works fine if you specify the correct config variables in wepay.yml, but it took a while to realize that my development environment issues were coming from the fact that the config variables I had set were not referenced.

**Comment by adamthedeveloper** [comment]
oops. Ok - I guess someone changed the key but didn't change the wepay.yml template for new installs. Thanks for bringing this to our attention. I'll get it fixed.

**Comment by SteveAquino** [comment]
Strange, I see the correct endpoints for this in the template/wepay.yml file.  Is there something else we're missing?

**Comment by SteveAquino** [comment]
OK I'm closing this because things seem to be working properly and I'm guessing it's a typo or something in your code.  If you're still having errors, maybe show us how you're using it.
