### ISSUE TITLE
Clarity on error

### ISSUE THREAD

**Issue by nemild** [adamthedeveloper/wepay-rails#28]
I am accessing the link that should redirect me to WePay, but keep getting this error message in Rails: Errno::ECONNRESET in Purchase::CheckoutController#index

Connection reset by peer

I'm assuming this is due to some bad auth. Am I correct in this assumption, and if so, is there an easy way to triangulate what's going wrong?

**Comment by adamthedeveloper** [comment]
Hmmm....Can you paste in your wepay.yml file?
