### ISSUE TITLE
install error - missing HTTParty

### ISSUE THREAD

**Issue by gabecoyne** [adamthedeveloper/wepay-rails#5]
script/rails g wepay_rails:install

/Library/Ruby/Gems/1.8/gems/aws-s3-0.6.2/lib/aws/s3/extensions.rb:206:in `const_missing': uninitialized constant WepayRails::Payments::Gateway::HTTParty (NameError)

```
from /Library/Ruby/Gems/1.8/gems/wepay-rails-2.1.0/lib/wepay-rails.rb:36
from /Library/Ruby/Gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:68:in `require'
from /Library/Ruby/Gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:68:in `require'
from /Library/Ruby/Gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:66:in `each'
from /Library/Ruby/Gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:66:in `require'
from /Library/Ruby/Gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:55:in `each'
from /Library/Ruby/Gems/1.8/gems/bundler-1.0.15/lib/bundler/runtime.rb:55:in `require'
from /Library/Ruby/Gems/1.8/gems/bundler-1.0.15/lib/bundler.rb:120:in `require'
```

I tried adding httparty to the gemfile and that didn't help.

Not sure what the issue is... I'm running Ruby 1.8.7 and Rails 3.0.9

**Comment by adamthedeveloper** [comment]
Thanks for reporting this. Can you do me a HUGE favor and add:

require 'httparty'

to the top of your lib / wepay-rails.rb file in your gems directory?

Let me know if that works - if so, I will add the require to the code and patch it.

**Comment by gabecoyne** [comment]
Thanks for the fast response! That did it!

**Comment by adamthedeveloper** [comment]
You got it buddy! Thanks for turning in the bug. I'll add the line and push a patch tonight.

**Comment by adamthedeveloper** [comment]
added require at the top of wepay-rails.rb. Marking as fixed.

**Comment by gabecoyne** [comment]
Thanks Adam.

**Comment by adamthedeveloper** [comment]
You got it. Let me know how the gem works out for you.  Adam
